name: pycommute
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - jupyter
  - notebook
  - matplotlib
  - numpy
  - pip
  - python=3.7.6
  - pytz
  - gmaps
  - pandas
  - pip:
    - googlemaps

